name: Deploy
# execute workflow after push to main
on:
  push:
    branches: [main]  
#necessary perms
permissions:
  contents: read          
  pages: write          
  id-token: write         
#build with astro and deploy to gh pages
jobs:
  #build the site, using node as package manager
  astro-build:
    name: Build astro site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build with Astro
        run: npm run build
      - name: Create artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
  publish-site:
    name: Publish to GitHub Pages
    needs: astro-build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy using GitHub Pages 
        id: deploy
        uses: actions/deploy-pages@v4

